stages:
    run:
        cmd: nextflow run https://github.com/TARGENE/targene-pipeline -entry NULL_SIMULATION -r 3ba6a5a6c8760ddfa99cc22cc82b4c9237c7427a -profile eddie -resume -c ../assets/simulation.config -with-trace -with-report -N s2042526@ed.ac.uk
        deps:
            - ../assets
            - /exports/igmm/eddie/UK-BioBank-53116/imputed/ukb_snp_qc.txt
            - /exports/igmm/eddie/UK-BioBank-53116/phenotypes/ukb45981.enc_ukb
            - /exports/igmm/eddie/UK-BioBank-53116/phenotypes/encoding.ukb
            - /exports/igmm/eddie/UK-BioBank-53116/imputed/ukb_53116_chr1.bgen
            - /exports/igmm/eddie/UK-BioBank-53116/genotypes/ukb_53116_chr1.bed
