traits:
  - fields:
      - "41202"
      - "41204"
    phenotypes:
      - name: "G20 Parkinson's disease"
        codings:
          - "G20"
      - name: "G35 Multiple sclerosis"
        codings:
          - "G35"
      - name: "K90-K93 Other diseases of the digestive system"
        codings:
          - "K90"
          - "K900"
          - "K901"
          - "K902"
          - "K903"
          - "K904"
          - "K908"
          - "K909"
          - "K91"
          - "K910"
          - "K911"
          - "K912"
          - "K913"
          - "K914"
          - "K915"
          - "K918"
          - "K919"
          - "K92"
          - "K920"
          - "K921"
          - "K922"
          - "K928"
          - "K929"
          - "K93"
          - "K930"
          - "K931"
          - "K938"
      - name: "H00-H06 Disorders of eyelid, lacrimal system and orbit"
        codings:
          - "H028"
          - "H029"
          - "H03"
          - "H030"
          - "H031"
          - "H038"
          - "H04"
          - "H040"
          - "H041"
          - "H042"
          - "H043"
          - "H044"
          - "H045"
          - "H046"
          - "H048"
          - "H049"
          - "H05"
          - "H050"
          - "H051"
          - "H052"
          - "H053"
          - "H054"
          - "H055"
          - "H058"
          - "H059"
          - "H06"
          - "H060"
          - "H061"
          - "H062"
          - "H063"
          - "H00"
          - "H000"
          - "H001"
          - "H01"
          - "H010"
          - "H011"
          - "H018"
          - "H019"
          - "H02"
          - "H020"
          - "H021"
          - "H022"
          - "H023"
          - "H024"
          - "H025"
          - "H026"
          - "H027"
  - fields:
      - "20002"
    phenotypes:
      - name: "sarcoidosis"
        codings:
          - "1371"
      - name: "type 2 diabetes"
        codings:
          - "1223"
      - name: "psoriasis"
        codings:
          - "1453"
  - fields:
      - "30000"
    phenotypes:
      - name: "White blood cell (leukocyte) count"
  - fields:
      - "23127"
    phenotypes:
      - name: "Trunk fat percentage"
  - fields:
      - "21001"
    phenotypes:
      - name: "Body mass index (BMI)"
  - fields:
      - "1717"
    phenotypes:
      - name: "Skin colour"
  - fields:
      - "21003"
    phenotypes:
      - name: "Age-Assessment"
  - fields:
      - "22001"
    phenotypes:
      - name: "Genetic-Sex"

  